import { Venue, Task, EpwItem } from "./types";

function task(id: string, venueId: string, type: Task["type"], question: string, options?: string[]): Task {
  return { id, type, question, options, venueId };
}

export const MOCK_VENUES: Venue[] = [
  {
    id: "v1", name: "Koffee", address: "1 La Vuelta, Orinda, CA",
    lat: 37.8784, lng: -122.1796, category: "Coffee Shop",
    tags: ["Chains"],
    tasks: [task("t1", "v1", "confirm_category", "Is 'Coffee Shop' the correct category for this venue?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    claimed: true,
    detail: {
      phone: "415-555-6578",
      hours: [
        { day: "Mon - Thu", hours: "9 am - 8 pm" },
        { day: "Fri", hours: "10 am - 8 pm" },
        { day: "Sat", hours: "9 am - 11 pm" },
        { day: "Sun", hours: "9 am - 11 pm" },
      ],
      website: "http://www.koffee-orinda.com",
      facebook: "koffeecafe",
      instagram: "@koffeecafe",
      features: ["Reservation", "Credit card: Master, Visa, AMEX", "Outdoor seating"],
      fsqPlaceId: "4aff17aaf964a520143422e3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 1,
      suggestedAddress: "10 La Vuelta, Orinda, CA 94563",
      suggestedPhone: "415-555-6573",
      suggestedHours: [
        { day: "Mon - Thu", hours: "8 am - 8 pm" },
        { day: "Fri", hours: "10 am - 9 pm" },
        { day: "Sat", hours: "9 am - 11 pm" },
        { day: "Sun", hours: "9 am - 10 pm" },
      ],
      categories: ["Coffee Shop", "Cafe"],
      suggestedCategories: ["Coffee Shop", "Cafe", "Bakery"],
      suggestedLat: 37.8792,
      suggestedLng: -122.1783,
    },
  },
  {
    id: "v2", name: "901 Columbus Cafe", address: "900 North Point St #100, San Francisco, CA",
    lat: 37.8060, lng: -122.4228, category: "Cafe",
    tags: ["Flagged", "Categories", "Chains"],
    parentVenue: { id: "v41", name: "Ghirardelli Square" },
    tasks: [
      task("t2", "v2", "confirm_category", "Is 'Cafe' the correct category?", ["Yes", "No", "Not sure"]),
      task("t3", "v2", "verify_address", "Is '901 Columbus Ave' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    claimed: true,
    detail: {
      phone: "415-986-1886",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 5 pm" },
      ],
      website: "http://www.901columbuscafe.com",
      facebook: "901columbusCafe",
      instagram: "@901columbus",
      features: ["Wi-Fi", "Credit card: Visa, AMEX"],
      fsqPlaceId: "4bf58dd8d48988d1e0931735",
      uniqueVisitors: 3,
      totalCheckins: 4,
      visitedLast60Days: 2,
      suggestedAddress: "901 Columbus Ave, Suite B, San Francisco, CA 94133",
      suggestedPhone: "415-986-1890",
      suggestedHours: [
        { day: "Mon - Fri", hours: "6:30 am - 6 pm" },
        { day: "Sat - Sun", hours: "7 am - 5 pm" },
      ],
      categories: ["Cafe", "Italian Restaurant"],
      suggestedCategories: ["Cafe", "Italian Restaurant", "Breakfast Spot"],
      suggestedLat: 37.8068,
      suggestedLng: -122.4215,
    },
  },
  {
    id: "v3", name: "Baja Cali Taqueria & Grill", address: "1 La Vuelta, Orinda, CA",
    lat: 37.8801, lng: -122.1820, category: "Mexican Restaurant",
    tags: ["Details", "Attributes"],
    tasks: [task("t4", "v3", "confirm_hours", "Are the hours Mon-Sat 9AM-9PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    claimed: true,
    detail: {
      phone: "925-254-1331",
      hours: [
        { day: "Mon - Sat", hours: "9 am - 9 pm" },
        { day: "Sun", hours: "10 am - 8 pm" },
      ],
      website: "http://www.bajacalitaqueria.com",
      instagram: "@bajacalitaqueria",
      features: ["Outdoor seating", "Takeout", "Credit card: Visa, Master"],
      fsqPlaceId: "4c2c0732f964a5209ea93ee3",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedAddress: "1 La Vuelta, Suite 2, Orinda, CA 94563",
      suggestedPhone: "925-254-1335",
      suggestedHours: [
        { day: "Sun", hours: "10 am - 8 pm" },
      ],
      categories: ["Mexican Restaurant", "Taco Place"],
      suggestedCategories: ["Mexican Restaurant", "Taco Place", "Fast Food"],
    },
  },
  {
    id: "v4", name: "Tartine Bakery", address: "600 Guerrero St, San Francisco, CA",
    lat: 37.7613, lng: -122.4243, category: "Bakery",
    tags: ["Details"],
    tasks: [
      task("t5", "v4", "verify_address", "Is '600 Guerrero St' the correct address?", ["Yes", "No", "Not sure"]),
      task("t5b", "v4", "confirm_hours", "Are the hours 8AM-7PM Mon-Fri correct?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    claimed: true,
    detail: {
      phone: "415-487-2600",
      hours: [
        { day: "Mon - Fri", hours: "8 am - 7 pm" },
        { day: "Sat - Sun", hours: "9 am - 8 pm" },
      ],
      website: "http://www.tartinebakery.com",
      instagram: "@tartinebakery",
      features: ["Credit card: Master, Visa, AMEX", "Outdoor seating"],
      fsqPlaceId: "40a55d80f964a52020f31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 3,
      suggestedAddress: "602 Guerrero St, San Francisco, CA",
      suggestedPhone: "415-487-2601",
      suggestedHours: [
        { day: "Mon - Fri", hours: "7:30 am - 7 pm" },
        { day: "Sat - Sun", hours: "8 am - 8 pm" },
      ],
    },
  },
  {
    id: "v5", name: "Blue Bottle Coffee", address: "66 Mint St, San Francisco, CA",
    lat: 37.7824, lng: -122.4058, category: "Coffee Shop",
    tags: ["Chains", "Categories"],
    tasks: [task("t6", "v5", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    claimed: true,
    detail: {
      phone: "510-653-3394",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 5 pm" },
      ],
      website: "http://www.bluebottlecoffee.com",
      facebook: "bluebottlecoffee",
      instagram: "@bluebottle",
      features: ["Wi-Fi", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "4b12c5f4f964a5204ba723e3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
      suggestedAddress: "66 Mint St, Floor 1, San Francisco, CA 94103",
      suggestedPhone: "510-653-3399",
      suggestedHours: [
        { day: "Mon - Fri", hours: "7 am - 5:30 pm" },
        { day: "Sat - Sun", hours: "8 am - 4:30 pm" },
      ],
    },
  },
  {
    id: "v6", name: "Bi-Rite Creamery", address: "3692 18th St, San Francisco, CA",
    lat: 37.7617, lng: -122.4256, category: "Ice Cream Shop",
    tags: ["Details", "Attributes"],
    tasks: [
      task("t7", "v6", "confirm_hours", "Are hours 11AM-10PM daily correct?", ["Yes", "No", "Not sure"]),
      task("t7b", "v6", "verify_address", "Is '3692 18th St' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-626-5600",
      hours: [{ day: "Daily", hours: "11 am - 10 pm" }],
      website: "http://www.biritecreamery.com",
      instagram: "@biritecreamery",
      features: ["Credit card: Visa, Master", "Outdoor seating"],
      fsqPlaceId: "49d4fb90f964a520b85d1fe3",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "3692 18th St, Suite A, San Francisco, CA",
      suggestedPhone: "415-626-5601",
      suggestedHours: [
        { day: "Sun - Thu", hours: "11 am - 9 pm" },
        { day: "Fri - Sat", hours: "11 am - 10 pm" },
      ],
    },
  },
  {
    id: "v7", name: "Foreign Cinema", address: "2534 Mission St, San Francisco, CA",
    lat: 37.77493, lng: -122.41942, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t8", "v7", "confirm_category", "Is 'Restaurant' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-648-7600",
      hours: [
        { day: "Mon - Thu", hours: "5:30 pm - 10 pm" },
        { day: "Fri - Sat", hours: "5:30 pm - 11 pm" },
        { day: "Sun", hours: "11 am - 3 pm, 5:30 pm - 10 pm" },
      ],
      website: "http://www.foreigncinema.com",
      facebook: "foreigncinema",
      instagram: "@foreigncinema",
      features: ["Reservation", "Outdoor seating", "Full bar"],
      fsqPlaceId: "3fd66200f964a520a0ec1ee3",
      uniqueVisitors: 4,
      totalCheckins: 5,
      visitedLast60Days: 2,
      suggestedAddress: "2534 Mission St, San Francisco, CA 94110",
      suggestedPhone: "415-648-7610",
      suggestedHours: [
        { day: "Mon - Thu", hours: "5:30 pm - 10 pm" },
        { day: "Fri - Sat", hours: "5 pm - 11 pm" },
        { day: "Sun", hours: "11 am - 3 pm, 5 pm - 10 pm" },
      ],
    },
  },
  {
    id: "v8", name: "Dolores Park Cafe", address: "501 Dolores St, San Francisco, CA",
    lat: 37.7610, lng: -122.4272, category: "Cafe",
    tags: ["Flagged"],
    tasks: [
      task("t9", "v8", "fix_coordinates", "Does the pin location look correct on the map?", ["Yes", "No", "Not sure"]),
      task("t9b", "v8", "confirm_category", "Is 'Cafe' the correct category?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-621-2936",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 7 pm" },
        { day: "Sat - Sun", hours: "8 am - 7 pm" },
      ],
      features: ["Wi-Fi", "Outdoor seating"],
      fsqPlaceId: "42377700f964a52069221fe3",
      uniqueVisitors: 3,
      totalCheckins: 2,
      visitedLast60Days: 1,
      suggestedAddress: "501 Dolores St #1, San Francisco, CA",
      suggestedPhone: "415-621-2940",
      suggestedHours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 6 pm" },
      ],
    },
  },
  {
    id: "v9", name: "Delfina", address: "3621 18th St, San Francisco, CA",
    lat: 37.7618, lng: -122.4247, category: "Italian Restaurant",
    tags: ["Categories"],
    tasks: [task("t10", "v9", "verify_address", "Is '3621 18th St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
    detail: {
      phone: "415-552-4055",
      hours: [
        { day: "Tue - Sat", hours: "5:30 pm - 10 pm" },
        { day: "Sun - Mon", hours: "Closed" },
      ],
      website: "http://www.delfinasf.com",
      instagram: "@delfinarestaurant",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "3fd66200f964a520bde31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 2,
      suggestedAddress: "3621 18th St, San Francisco, CA 94110",
      suggestedPhone: "415-552-4060",
      suggestedHours: [
        { day: "Tue - Sat", hours: "5 pm - 10 pm" },
        { day: "Sun - Mon", hours: "Closed" },
      ],
    },
  },
  {
    id: "v10", name: "Philz Coffee", address: "3101 24th St, San Francisco, CA",
    lat: 37.7526, lng: -122.4184, category: "Coffee Shop",
    tags: ["Chains"],
    tasks: [
      task("t11", "v10", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"]),
      task("t11b", "v10", "verify_address", "Is '3101 24th St' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-875-9370",
      hours: [
        { day: "Mon - Fri", hours: "6 am - 7:30 pm" },
        { day: "Sat - Sun", hours: "6:30 am - 7:30 pm" },
      ],
      website: "http://www.philzcoffee.com",
      facebook: "philzcoffee",
      instagram: "@philzcoffee",
      features: ["Wi-Fi", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "4a83a0b6f964a520f4fb1fe3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 5,
      suggestedAddress: "3101 24th St, San Francisco, CA 94110",
      suggestedPhone: "415-875-9371",
      suggestedHours: [
        { day: "Mon - Fri", hours: "5:30 am - 7:30 pm" },
        { day: "Sat - Sun", hours: "6 am - 7:30 pm" },
      ],
    },
  },
  {
    id: "v11", name: "La Taqueria", address: "2889 Mission St, San Francisco, CA",
    lat: 37.7508, lng: -122.4181, category: "Taqueria",
    tags: ["Details", "Categories"],
    tasks: [task("t12", "v11", "confirm_category", "Is 'Taqueria' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-285-7117",
      hours: [{ day: "Daily", hours: "11 am - 9 pm" }],
      features: ["Cash only", "Outdoor seating"],
      fsqPlaceId: "3fd66200f964a520b1e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
      suggestedAddress: "2889 Mission St, San Francisco, CA 94110",
      suggestedPhone: "415-285-7120",
      suggestedHours: [
        { day: "Daily", hours: "11 am - 8:30 pm" },
      ],
    },
  },
  {
    id: "v12", name: "Sightglass Coffee", address: "270 7th St, San Francisco, CA",
    lat: 37.7772, lng: -122.4068, category: "Coffee Shop",
    tags: ["Chains", "Details"],
    tasks: [
      task("t13", "v12", "verify_address", "Is '270 7th St' the correct address?", ["Yes", "No", "Not sure"]),
      task("t13b", "v12", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-861-1313",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 6 pm" },
      ],
      website: "http://www.sightglasscoffee.com",
      instagram: "@sightglasscoffee",
      features: ["Wi-Fi", "Credit card: Visa, Master"],
      fsqPlaceId: "4c04bbd8a1010f477dba0ef2",
      uniqueVisitors: 4,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "270 7th St, Floor 1, San Francisco, CA",
      suggestedPhone: "415-861-1320",
      suggestedHours: [
        { day: "Mon - Fri", hours: "7 am - 5:30 pm" },
        { day: "Sat - Sun", hours: "8 am - 5:30 pm" },
      ],
    },
  },
  {
    id: "v13", name: "Zuni Cafe", address: "1658 Market St, San Francisco, CA",
    lat: 37.7736, lng: -122.4215, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t14", "v13", "confirm_hours", "Are hours Tue-Sun 11:30AM-11PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-552-2522",
      hours: [
        { day: "Tue - Sun", hours: "11:30 am - 11 pm" },
        { day: "Mon", hours: "Closed" },
      ],
      website: "http://www.zunicafe.com",
      facebook: "zunicafe",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "3fd66200f964a52096e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 3,
      suggestedAddress: "1658 Market St, San Francisco, CA 94102",
      suggestedPhone: "415-552-2525",
      suggestedHours: [
        { day: "Fri - Sat", hours: "11:30 am - 11 pm" },
        { day: "Sun", hours: "11 am - 10 pm" },
        { day: "Mon", hours: "Closed" },
      ],
    },
  },
  {
    id: "v14", name: "Ritual Coffee Roasters", address: "1026 Valencia St, San Francisco, CA",
    lat: 37.7565, lng: -122.4214, category: "Coffee Shop",
    tags: ["Categories"],
    tasks: [task("t15", "v14", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-641-1024",
      hours: [
        { day: "Mon - Fri", hours: "6:30 am - 7 pm" },
        { day: "Sat - Sun", hours: "7 am - 7 pm" },
      ],
      website: "http://www.ritualroasters.com",
      instagram: "@ritualcoffee",
      features: ["Wi-Fi", "Credit card: Visa, Master"],
      fsqPlaceId: "42d4b3e0f964a520cd251fe3",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedAddress: "1026 Valencia St, San Francisco, CA 94110",
      suggestedPhone: "415-641-1030",
      suggestedHours: [
        { day: "Mon - Fri", hours: "6 am - 7 pm" },
        { day: "Sat - Sun", hours: "7 am - 6 pm" },
      ],
    },
  },
  {
    id: "v15", name: "Nopa", address: "560 Divisadero St, San Francisco, CA",
    lat: 37.7745, lng: -122.4378, category: "Restaurant",
    tags: ["Details", "Attributes"],
    tasks: [
      task("t16", "v15", "fix_coordinates", "Does the pin location look correct?", ["Yes", "No", "Not sure"]),
      task("t16b", "v15", "confirm_hours", "Are hours Mon-Fri 6PM-1AM correct?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-864-8643",
      hours: [
        { day: "Mon - Fri", hours: "6 pm - 1 am" },
        { day: "Sat - Sun", hours: "11 am - 1 am" },
      ],
      website: "http://www.nopasf.com",
      facebook: "nopasf",
      instagram: "@nopasf",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "44b22a15f964a520f7321fe3",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 2,
      suggestedAddress: "560 Divisadero St, San Francisco, CA 94117",
      suggestedPhone: "415-864-8650",
      suggestedHours: [
        { day: "Sat - Sun", hours: "11 am - 12 am" },
      ],
    },
  },
  {
    id: "v16", name: "Flour + Water", address: "2401 Harrison St, San Francisco, CA",
    lat: 37.7590, lng: -122.4132, category: "Italian Restaurant",
    tags: ["Details"],
    tasks: [task("t17", "v16", "verify_address", "Is '2401 Harrison St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-826-7000",
      hours: [
        { day: "Mon - Thu", hours: "5:30 pm - 10 pm" },
        { day: "Fri - Sat", hours: "5:30 pm - 10:30 pm" },
        { day: "Sun", hours: "5 pm - 9:30 pm" },
      ],
      website: "http://www.flourandwater.com",
      instagram: "@flourandwater",
      features: ["Reservation", "Full bar"],
      fsqPlaceId: "4bcc0390cc8cd13a2e1f8cf7",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "2401 Harrison St, San Francisco, CA 94110",
      suggestedPhone: "415-826-7005",
      suggestedHours: [
        { day: "Mon - Thu", hours: "5:30 pm - 9:30 pm" },
        { day: "Fri - Sat", hours: "5 pm - 10:30 pm" },
        { day: "Sun", hours: "5 pm - 9 pm" },
      ],
    },
  },
  {
    id: "v17", name: "Trick Dog", address: "3010 20th St, San Francisco, CA",
    lat: 37.7586, lng: -122.4220, category: "Bar",
    tags: ["Categories", "Flagged"],
    tasks: [task("t18", "v17", "confirm_category", "Is 'Bar' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-471-2999",
      hours: [{ day: "Daily", hours: "3 pm - 2 am" }],
      website: "http://www.trickdogbar.com",
      instagram: "@trickdogbar",
      features: ["Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "51756e5de4b0bb59b25d062a",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedAddress: "3010 20th St, San Francisco, CA 94110",
      suggestedPhone: "415-471-3000",
      suggestedHours: [
        { day: "Daily", hours: "3 pm - 1:30 am" },
      ],
    },
  },
  {
    id: "v18", name: "Humphry Slocombe", address: "2790 Harrison St, San Francisco, CA",
    lat: 37.7536, lng: -122.4133, category: "Ice Cream Shop",
    tags: ["Details"],
    tasks: [task("t19", "v18", "confirm_hours", "Are hours 12PM-9PM daily correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
    detail: {
      phone: "415-550-6971",
      hours: [{ day: "Daily", hours: "12 pm - 9 pm" }],
      website: "http://www.humphryslocombe.com",
      facebook: "humphryslocombe",
      instagram: "@humphryslocombe",
      features: ["Credit card: Visa, Master"],
      fsqPlaceId: "4ad4c05ff964a520b7f220e3",
      uniqueVisitors: 4,
      totalCheckins: 4,
      visitedLast60Days: 2,
      suggestedAddress: "2790 Harrison St, San Francisco, CA 94110",
      suggestedPhone: "415-550-6975",
      suggestedHours: [
        { day: "Daily", hours: "12 pm - 8 pm" },
      ],
    },
  },
  {
    id: "v19", name: "Anchor Brewing", address: "1705 Mariposa St, San Francisco, CA",
    lat: 37.7638, lng: -122.3979, category: "Brewery",
    tags: ["Chains", "Attributes"],
    tasks: [task("t20", "v19", "confirm_category", "Is 'Brewery' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-863-8350",
      hours: [
        { day: "Mon - Fri", hours: "12 pm - 9 pm" },
        { day: "Sat", hours: "11 am - 9 pm" },
        { day: "Sun", hours: "Closed" },
      ],
      website: "http://www.anchorbrewing.com",
      facebook: "anchorbrewing",
      instagram: "@anchorbrewing",
      features: ["Taproom", "Tours", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "3fd66200f964a52096e81ee3",
      uniqueVisitors: 3,
      totalCheckins: 3,
      visitedLast60Days: 1,
      suggestedAddress: "1705 Mariposa St, San Francisco, CA 94107",
      suggestedPhone: "415-863-8355",
      suggestedHours: [
        { day: "Mon - Fri", hours: "12 pm - 8 pm" },
        { day: "Sat", hours: "11 am - 8 pm" },
        { day: "Sun", hours: "Closed" },
      ],
    },
  },
  {
    id: "v20", name: "Dandelion Chocolate", address: "740 Valencia St, San Francisco, CA",
    lat: 37.7609, lng: -122.4216, category: "Chocolate Shop",
    tags: ["Details", "Attributes"],
    tasks: [
      task("t21", "v20", "verify_address", "Is '740 Valencia St' the correct address?", ["Yes", "No", "Not sure"]),
      task("t21b", "v20", "confirm_hours", "Are hours 10AM-9PM daily correct?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-349-0942",
      hours: [{ day: "Daily", hours: "10 am - 9 pm" }],
      website: "http://www.dandelionchocolate.com",
      facebook: "dandelionchocolate",
      instagram: "@dandelionchocolate",
      features: ["Wi-Fi", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "4fb3c2fbe4b0d0766b56fb8b",
      uniqueVisitors: 5,
      totalCheckins: 4,
      visitedLast60Days: 3,
      suggestedAddress: "740 Valencia St, San Francisco, CA 94110",
      suggestedPhone: "415-349-0945",
      suggestedHours: [
        { day: "Daily", hours: "10 am - 8 pm" },
      ],
    },
  },
  {
    id: "v21", name: "Nopalito", address: "306 Broderick St, San Francisco, CA",
    lat: 37.7725, lng: -122.4397, category: "Mexican Restaurant",
    tags: ["Categories"],
    tasks: [task("t22", "v21", "confirm_category", "Is 'Mexican Restaurant' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-437-0303",
      hours: [
        { day: "Mon - Fri", hours: "11:30 am - 10 pm" },
        { day: "Sat - Sun", hours: "11 am - 10 pm" },
      ],
      website: "http://www.nopalitosf.com",
      instagram: "@nopalitosf",
      features: ["Reservation", "Credit card: Visa, Master"],
      fsqPlaceId: "4b88ddbaf964a520953932e3",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedAddress: "306 Broderick St, San Francisco, CA 94117",
      suggestedPhone: "415-437-0310",
      suggestedHours: [
        { day: "Mon - Fri", hours: "11:30 am - 9:30 pm" },
        { day: "Sat - Sun", hours: "11 am - 9:30 pm" },
      ],
    },
  },
  {
    id: "v22", name: "Piccino", address: "1001 Minnesota St, San Francisco, CA",
    lat: 37.7554, lng: -122.3897, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t23", "v22", "fix_coordinates", "Does the pin location look correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-824-4224",
      hours: [
        { day: "Tue - Sat", hours: "11:30 am - 9 pm" },
        { day: "Sun - Mon", hours: "Closed" },
      ],
      website: "http://www.piccinocafe.com",
      instagram: "@piccinocafe",
      features: ["Outdoor seating", "Credit card: Visa, Master"],
      fsqPlaceId: "43cbabd0f964a520cd2d1fe3",
      uniqueVisitors: 3,
      totalCheckins: 2,
      visitedLast60Days: 1,
      suggestedAddress: "1001 Minnesota St, San Francisco, CA 94107",
      suggestedPhone: "415-824-4230",
      suggestedHours: [
        { day: "Tue - Sat", hours: "11 am - 9 pm" },
        { day: "Sun - Mon", hours: "Closed" },
      ],
    },
  },
  {
    id: "v23", name: "Lazy Bear", address: "3416 19th St, San Francisco, CA",
    lat: 37.7600, lng: -122.4220, category: "Restaurant",
    tags: ["Details", "Attributes"],
    tasks: [task("t24", "v23", "confirm_hours", "Are hours Wed-Sun 6PM-10PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-874-9921",
      hours: [
        { day: "Wed - Sun", hours: "6 pm - 10 pm" },
        { day: "Mon - Tue", hours: "Closed" },
      ],
      website: "http://www.lazybearsf.com",
      instagram: "@lazybearsf",
      features: ["Reservation required", "Tasting menu", "Full bar"],
      fsqPlaceId: "53e6e48e498ea3e1fde0bcdf",
      uniqueVisitors: 3,
      totalCheckins: 2,
      visitedLast60Days: 1,
      suggestedAddress: "3416 19th St, San Francisco, CA 94110",
      suggestedPhone: "415-874-9925",
      suggestedHours: [
        { day: "Mon - Tue", hours: "Closed" },
      ],
    },
  },
  {
    id: "v24", name: "Craftsman and Wolves", address: "746 Valencia St, San Francisco, CA",
    lat: 37.7607, lng: -122.4217, category: "Bakery",
    tags: ["Categories", "Details"],
    tasks: [task("t25", "v24", "confirm_category", "Is 'Bakery' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-913-7713",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 4 pm" },
        { day: "Sat - Sun", hours: "8 am - 4 pm" },
      ],
      website: "http://www.craftsman-wolves.com",
      instagram: "@craftsmanwolves",
      features: ["Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "513fd6c8e4b0d49fdd0f50c0",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedAddress: "746 Valencia St, San Francisco, CA 94110",
      suggestedPhone: "415-913-7720",
      suggestedHours: [
        { day: "Mon - Fri", hours: "7 am - 3 pm" },
        { day: "Sat - Sun", hours: "8 am - 3 pm" },
      ],
    },
  },
  {
    id: "v25", name: "State Bird Provisions", address: "1529 Fillmore St, San Francisco, CA",
    lat: 37.7835, lng: -122.4324, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t26", "v25", "verify_address", "Is '1529 Fillmore St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-795-1272",
      hours: [
        { day: "Mon - Sat", hours: "5:30 pm - 10 pm" },
        { day: "Sun", hours: "Closed" },
      ],
      website: "http://www.statebirdsf.com",
      instagram: "@statebirdprovisions",
      features: ["Reservation", "Full bar", "Credit card: Visa, Master, AMEX"],
      fsqPlaceId: "5065ca35e4b0a8f1e19a8fba",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 1,
      suggestedAddress: "1529 Fillmore St, San Francisco, CA 94115",
      suggestedPhone: "415-795-1280",
      suggestedHours: [
        { day: "Mon - Sat", hours: "5:30 pm - 9:30 pm" },
        { day: "Sun", hours: "Closed" },
      ],
    },
  },
  {
    id: "v26", name: "El Farolito", address: "2779 Mission St, San Francisco, CA",
    lat: 37.7521, lng: -122.4181, category: "Taqueria",
    tags: ["Flagged", "Details"],
    tasks: [task("t27", "v26", "confirm_category", "Is 'Taqueria' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-824-7877",
      hours: [{ day: "Daily", hours: "10 am - 3 am" }],
      features: ["Cash preferred", "Late night"],
      fsqPlaceId: "3fd66200f964a52099e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
      suggestedAddress: "2779 Mission St, San Francisco, CA 94110",
      suggestedPhone: "415-824-7880",
      suggestedHours: [
        { day: "Daily", hours: "10 am - 2:30 am" },
      ],
    },
  },
  {
    id: "v27", name: "Toronado", address: "547 Haight St, San Francisco, CA",
    lat: 37.7717, lng: -122.4316, category: "Bar",
    tags: ["Categories"],
    tasks: [task("t28", "v27", "fix_coordinates", "Does the pin location look correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-863-2276",
      hours: [{ day: "Daily", hours: "11:30 am - 2 am" }],
      website: "http://www.toronado.com",
      features: ["Cash only", "Craft beer"],
      fsqPlaceId: "3fd66200f964a52082e31ee3",
      uniqueVisitors: 4,
      totalCheckins: 4,
      visitedLast60Days: 2,
      suggestedAddress: "547 Haight St, San Francisco, CA 94117",
      suggestedPhone: "415-863-2280",
      suggestedHours: [
        { day: "Daily", hours: "11:30 am - 1:30 am" },
      ],
    },
  },
  {
    id: "v28", name: "Four Barrel Coffee", address: "375 Valencia St, San Francisco, CA",
    lat: 37.7664, lng: -122.4220, category: "Coffee Shop",
    tags: ["Chains"],
    tasks: [task("t29", "v28", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-252-0800",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 6 pm" },
        { day: "Sat - Sun", hours: "8 am - 6 pm" },
      ],
      website: "http://www.fourbarrelcoffee.com",
      instagram: "@fourbarrelcoffee",
      features: ["Wi-Fi", "Outdoor seating"],
      fsqPlaceId: "4a93fbb8f964a52023591fe3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 3,
      suggestedAddress: "375 Valencia St, San Francisco, CA 94103",
      suggestedPhone: "415-252-0805",
      suggestedHours: [
        { day: "Mon - Fri", hours: "7 am - 5:30 pm" },
        { day: "Sat - Sun", hours: "8 am - 5:30 pm" },
      ],
    },
  },
  {
    id: "v29", name: "Mitchell's Ice Cream", address: "688 San Jose Ave, San Francisco, CA",
    lat: 37.7440, lng: -122.4245, category: "Ice Cream Shop",
    tags: ["Details", "Attributes"],
    tasks: [task("t30", "v29", "confirm_hours", "Are hours 11AM-11PM daily correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: false,
    detail: {
      phone: "415-648-2300",
      hours: [{ day: "Daily", hours: "11 am - 11 pm" }],
      website: "http://www.mitchellsicecream.com",
      features: ["Cash and card", "Family owned"],
      fsqPlaceId: "3fd66200f964a520b3e31ee3",
      uniqueVisitors: 5,
      totalCheckins: 5,
      visitedLast60Days: 4,
      suggestedAddress: "688 San Jose Ave, San Francisco, CA 94110",
      suggestedPhone: "415-648-2305",
      suggestedHours: [
        { day: "Fri - Sat", hours: "11 am - 11 pm" },
      ],
    },
  },
  {
    id: "v30", name: "Plow", address: "1299 18th St, San Francisco, CA",
    lat: 37.7612, lng: -122.3903, category: "Breakfast Restaurant",
    tags: ["Categories", "Details"],
    tasks: [
      task("t31", "v30", "confirm_category", "Is 'Breakfast Restaurant' the correct category?", ["Yes", "No", "Not sure"]),
      task("t31b", "v30", "verify_address", "Is '1299 18th St' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    detail: {
      phone: "415-821-7569",
      hours: [
        { day: "Mon - Fri", hours: "7 am - 3 pm" },
        { day: "Sat - Sun", hours: "8 am - 3:30 pm" },
      ],
      website: "http://www.eatatplow.com",
      instagram: "@eatatplow",
      features: ["Credit card: Visa, Master", "Outdoor seating"],
      fsqPlaceId: "4c86e9a58b3d2d7f2c64661c",
      uniqueVisitors: 4,
      totalCheckins: 3,
      visitedLast60Days: 2,
      suggestedAddress: "1299 18th St, San Francisco, CA 94107",
      suggestedPhone: "415-821-7575",
      suggestedHours: [
        { day: "Mon - Fri", hours: "7 am - 2:30 pm" },
        { day: "Sat - Sun", hours: "8 am - 3 pm" },
      ],
    },
  },
  {
    id: "v31", name: "Chez Panisse", address: "1517 Shattuck Ave, Berkeley, CA",
    lat: 37.7795, lng: -122.4148, category: "Restaurant",
    tags: ["Details"],
    tasks: [task("t32", "v31", "confirm_hours", "Are hours Tue-Sat 5PM-10PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v32", name: "Tony's Pizza Napoletana", address: "1570 Stockton St, San Francisco, CA",
    lat: 37.7998, lng: -122.4094, category: "Pizza Place",
    tags: ["Details"],
    tasks: [task("t33", "v32", "verify_address", "Is '1570 Stockton St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v33", name: "Mama's on Washington Square", address: "1701 Stockton St, San Francisco, CA",
    lat: 37.8012, lng: -122.4099, category: "Breakfast Restaurant",
    tags: ["Categories"],
    tasks: [task("t34", "v33", "confirm_category", "Is 'Breakfast Restaurant' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v34", name: "Golden Boy Pizza", address: "542 Green St, San Francisco, CA",
    lat: 37.7994, lng: -122.4078, category: "Pizza Place",
    tags: ["Details"],
    tasks: [task("t35", "v34", "confirm_hours", "Are hours 11:30AM-12AM daily correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v35", name: "Hog Island Oyster Co", address: "1 Ferry Building, San Francisco, CA",
    lat: 37.7955, lng: -122.3935, category: "Seafood Restaurant",
    tags: ["Details", "Attributes"],
    tasks: [task("t36", "v35", "verify_address", "Is '1 Ferry Building' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v36", name: "Swan Oyster Depot", address: "1517 Polk St, San Francisco, CA",
    lat: 37.7909, lng: -122.4216, category: "Seafood Restaurant",
    tags: ["Categories"],
    tasks: [task("t37", "v36", "confirm_category", "Is 'Seafood Restaurant' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v37", name: "House of Prime Rib", address: "1906 Van Ness Ave, San Francisco, CA",
    lat: 37.7925, lng: -122.4231, category: "Steakhouse",
    tags: ["Details"],
    tasks: [task("t38", "v37", "confirm_hours", "Are hours Mon-Sun 5PM-10PM correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v38", name: "Brenda's French Soul Food", address: "652 Polk St, San Francisco, CA",
    lat: 37.7831, lng: -122.4191, category: "Restaurant",
    tags: ["Details", "Categories"],
    tasks: [task("t39", "v38", "verify_address", "Is '652 Polk St' the correct address?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v39", name: "Boudin Bakery", address: "160 Jefferson St, San Francisco, CA",
    lat: 37.8084, lng: -122.4149, category: "Bakery",
    tags: ["Chains"],
    tasks: [task("t40", "v39", "confirm_category", "Is 'Bakery' the correct category?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v40", name: "Ghirardelli Ice Cream", address: "900 North Point St, San Francisco, CA",
    lat: 37.8060, lng: -122.4228, category: "Ice Cream Shop",
    tags: ["Chains", "Details"],
    tasks: [task("t41", "v40", "confirm_hours", "Are hours 9AM-11PM daily correct?", ["Yes", "No", "Not sure"])],
    globallyCompleted: true,
  },
  {
    id: "v41", name: "Ghirardelli Square", address: "900 North Point St #100, San Francisco, CA",
    lat: 37.8060, lng: -122.4230, category: "Shopping Plaza",
    tags: ["Details", "Attributes"],
    tasks: [],
    globallyCompleted: true,
    detail: {
      phone: "415-775-5500",
      hours: [
        { day: "Mon - Thu", hours: "10 am - 9 pm" },
        { day: "Fri - Sat", hours: "10 am - 10 pm" },
        { day: "Sun", hours: "10 am - 6 pm" },
      ],
      website: "http://www.ghirardellisq.com",
      instagram: "@ghirardellisq",
      features: ["Parking", "Wheelchair Accessible", "Restrooms"],
      fsqPlaceId: "4a7ae3f0f964a520f8e51fe3",
      uniqueVisitors: 152,
      totalCheckins: 890,
      visitedLast60Days: 45,
      suggestedAddress: "900 North Point St, Suite 100, San Francisco, CA 94109",
      suggestedPhone: "415-775-5505",
      suggestedHours: [
        { day: "Sun", hours: "11 am - 7 pm" },
      ],
      categories: ["Shopping Plaza", "Tourist Attraction"],
      suggestedCategories: ["Shopping Plaza", "Tourist Attraction", "Landmark"],
    },
  },
  {
    id: "the-daily-grind", name: "The Daily Grind", address: "482 Hayes St, San Francisco, CA",
    lat: 37.7764, lng: -122.4246, category: "Coffee Shop",
    tags: ["Hours", "Categories"],
    tasks: [
      task("tdg-t1", "the-daily-grind", "confirm_hours", "Are these hours correct? Mon-Fri 6am-6pm, Sat-Sun 7am-5pm", ["Yes", "No", "Not sure"]),
      task("tdg-t2", "the-daily-grind", "confirm_category", "Is 'Coffee Shop' the correct category for this venue?", ["Yes", "No", "Not sure"]),
      task("tdg-t3", "the-daily-grind", "verify_address", "Is '482 Hayes St, San Francisco, CA' the correct address?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    claimed: false,
    detail: {
      phone: "415-555-2847",
      hours: [
        { day: "Mon - Fri", hours: "6 am - 6 pm" },
        { day: "Sat - Sun", hours: "7 am - 5 pm" },
      ],
      website: "http://www.thedailygrind-sf.com",
      features: ["Wi-Fi", "Outdoor seating", "Credit card accepted"],
      fsqPlaceId: "5bfa29c8f964a520e43425e3",
      uniqueVisitors: 12,
      totalCheckins: 34,
      visitedLast60Days: 8,
      categories: ["Coffee Shop"],
      suggestedCategories: ["Coffee Shop", "Cafe", "Breakfast Spot"],
    },
  },
  {
    id: "sunset-yoga-studio", name: "Sunset Yoga Studio", address: "1200 Irving St, San Francisco, CA",
    lat: 37.7637, lng: -122.4683, category: "Fitness",
    tags: ["Categories", "Hours"],
    tasks: [
      task("sys-t1", "sunset-yoga-studio", "confirm_category", "Is 'Fitness' the correct category or should it be 'Yoga Studio'?", ["Fitness", "Yoga Studio", "Gym", "Not sure"]),
      task("sys-t2", "sunset-yoga-studio", "confirm_hours", "Are these hours correct? Mon-Sat 6am-9pm, Sun 8am-6pm", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    claimed: false,
    detail: {
      phone: "415-555-9021",
      hours: [
        { day: "Mon - Sat", hours: "6 am - 9 pm" },
        { day: "Sun", hours: "8 am - 6 pm" },
      ],
      website: "http://www.sunsetyogasf.com",
      features: ["Mat rental", "Showers", "Locker rooms"],
      fsqPlaceId: "5cfa39d8f964a520f53426e3",
      uniqueVisitors: 8,
      totalCheckins: 22,
      visitedLast60Days: 5,
      categories: ["Fitness"],
      suggestedCategories: ["Yoga Studio", "Fitness", "Wellness Center"],
    },
  },
  {
    id: "verde-mexican-grill", name: "Verde Mexican Grill", address: "2035 Chestnut St, San Francisco, CA",
    lat: 37.8003, lng: -122.4378, category: "Restaurant",
    tags: ["Hours", "Categories", "Flagged"],
    tasks: [
      task("vmg-t1", "verde-mexican-grill", "confirm_hours", "Are these hours correct? Mon-Thu 11am-9pm, Fri-Sat 11am-10pm, Sun 11am-8pm", ["Yes", "No", "Not sure"]),
      task("vmg-t2", "verde-mexican-grill", "confirm_category", "Is 'Restaurant' the correct category or should it be more specific?", ["Restaurant", "Mexican Restaurant", "Fast Casual", "Not sure"]),
      task("vmg-t3", "verde-mexican-grill", "verify_address", "Is '2035 Chestnut St, San Francisco, CA' the correct address?", ["Yes", "No", "Not sure"]),
      task("vmg-t4", "verde-mexican-grill", "photo_verification", "Does this photo match the current appearance of the venue?", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    claimed: false,
    detail: {
      phone: "415-555-7734",
      hours: [
        { day: "Mon - Thu", hours: "11 am - 9 pm" },
        { day: "Fri - Sat", hours: "11 am - 10 pm" },
        { day: "Sun", hours: "11 am - 8 pm" },
      ],
      website: "http://www.verdemexicangrill.com",
      features: ["Outdoor seating", "Delivery", "Takeout"],
      fsqPlaceId: "5dfa49e8f964a520g63427e3",
      uniqueVisitors: 20,
      totalCheckins: 56,
      visitedLast60Days: 14,
      categories: ["Restaurant"],
      suggestedCategories: ["Mexican Restaurant", "Fast Casual", "Restaurant"],
    },
  },
  {
    id: "main-street-books", name: "Main Street Books", address: "540 Valencia St, San Francisco, CA",
    lat: 37.7642, lng: -122.4214, category: "Bookstore",
    tags: ["Hours"],
    tasks: [
      task("msb-t1", "main-street-books", "confirm_hours", "Are these hours correct? Mon-Sat 10am-8pm, Sun 11am-6pm", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    claimed: false,
    detail: {
      phone: "415-555-3312",
      hours: [
        { day: "Mon - Sat", hours: "10 am - 8 pm" },
        { day: "Sun", hours: "11 am - 6 pm" },
      ],
      website: "http://www.mainstreetbooks-sf.com",
      features: ["Author events", "Kids section", "Used books"],
      fsqPlaceId: "5efa59f8f964a520h73428e3",
      uniqueVisitors: 6,
      totalCheckins: 15,
      visitedLast60Days: 3,
      categories: ["Bookstore"],
      suggestedCategories: ["Bookstore", "Gift Shop"],
    },
  },
  {
    id: "bay-brew-coffee", name: "Bay Brew Coffee", address: "1890 Fillmore St, San Francisco, CA",
    lat: 37.7871, lng: -122.4334, category: "Coffee Shop",
    tags: ["Categories", "Hours"],
    tasks: [
      task("bbc-t1", "bay-brew-coffee", "confirm_category", "Is 'Coffee Shop' the correct category?", ["Yes", "No", "Not sure"]),
      task("bbc-t2", "bay-brew-coffee", "confirm_hours", "Are these hours correct? Daily 5:30am-7pm", ["Yes", "No", "Not sure"]),
    ],
    globallyCompleted: false,
    claimed: false,
    detail: {
      phone: "415-555-4498",
      hours: [
        { day: "Mon - Sun", hours: "5:30 am - 7 pm" },
      ],
      website: "http://www.baybrewcoffee.com",
      features: ["Drive-through", "Wi-Fi", "Pastries"],
      fsqPlaceId: "5ffa69g8f964a520i83429e3",
      uniqueVisitors: 15,
      totalCheckins: 42,
      visitedLast60Days: 11,
      categories: ["Coffee Shop"],
      suggestedCategories: ["Coffee Shop", "Cafe"],
    },
  },
];

const VERACITY_RATINGS = [1, 3, 4, 5, 5, 2, 3, 1, 5, 4, 2, 5, 3, 1, 4, 5, 2, 5, 3, 1, 4, 2, 5, 3, 5, 1, 4, 2, 5, 3, 5, 4, 5, 3, 5, 2, 5, 4, 3, 5, 4];
MOCK_VENUES.forEach((v, i) => { v.veracityRating = VERACITY_RATINGS[i % VERACITY_RATINGS.length]; });

export const INITIAL_COMPLETED_VENUES = [
  "v1", "v3", "v5", "v7", "v9",
  "v10", "v11", "v13", "v14", "v16",
  "v17", "v18", "v19", "v21", "v22",
];

import type { VenueWoe } from "./types";
import type { VenueGeoData } from "./types";

export const MOCK_GEO_TRANSLATIONS: VenueGeoData[] = [
  {
    venueId: "v1",
    userEnteredCity: "Orinda",
    userEnteredState: "CA",
    isGeographic: false,
    geoId: 0,
    woeType: 0,
    localLanguageOrdering: ["English", "Spanish", "French"],
    levels: [
      {
        level: "Neighborhood",
        usedAs: "Neighborhood",
        translations: [
          { isoCode: "en", language: "English", translation: "Orinda" },
          { isoCode: "es", language: "Spanish", translation: "Orinda" },
          { isoCode: "fr", language: "French", translation: "Orinda" },
          { isoCode: "de", language: "German", translation: "Orinda" },
          { isoCode: "ja", language: "Japanese", translation: "オリンダ" },
        ],
      },
      {
        level: "Locality",
        usedAs: "City",
        geonameId: 5378538,
        translations: [
          { isoCode: "en", language: "English", translation: "Orinda" },
          { isoCode: "es", language: "Spanish", translation: "Orinda" },
          { isoCode: "fr", language: "French", translation: "Orinda" },
          { isoCode: "de", language: "German", translation: "Orinda" },
          { isoCode: "ja", language: "Japanese", translation: "オリンダ" },
        ],
      },
      {
        level: "Admin Level 2",
        usedAs: null,
        geonameId: 5339268,
        translations: [
          { isoCode: "en", language: "English", translation: "Contra Costa County" },
          { isoCode: "fr", language: "French", translation: "Comté de Contra Costa" },
          { isoCode: "es", language: "Spanish", translation: "Condado de Contra Costa" },
          { isoCode: "de", language: "German", translation: "Contra Costa County" },
          { isoCode: "zh", language: "Chinese", translation: "康特拉科斯塔县" },
        ],
      },
      {
        level: "Admin Level 1",
        usedAs: "State",
        geonameId: 5332921,
        translations: [
          { isoCode: "en", language: "English", translation: "California" },
          { isoCode: "es", language: "Spanish", translation: "California" },
          { isoCode: "fr", language: "French", translation: "Californie" },
          { isoCode: "de", language: "German", translation: "Kalifornien" },
          { isoCode: "ja", language: "Japanese", translation: "カリフォルニア州" },
          { isoCode: "zh", language: "Chinese", translation: "加利福尼亚州" },
          { isoCode: "ko", language: "Korean", translation: "캘리포니아주" },
        ],
      },
      {
        level: "Country",
        usedAs: "Country",
        geonameId: 6252001,
        translations: [
          { isoCode: "en", language: "English", translation: "United States" },
          { isoCode: "es", language: "Spanish", translation: "Estados Unidos" },
          { isoCode: "fr", language: "French", translation: "États-Unis" },
          { isoCode: "de", language: "German", translation: "Vereinigte Staaten" },
          { isoCode: "ja", language: "Japanese", translation: "アメリカ合衆国" },
          { isoCode: "zh", language: "Chinese", translation: "美国" },
          { isoCode: "ko", language: "Korean", translation: "미국" },
          { isoCode: "pt", language: "Portuguese", translation: "Estados Unidos" },
        ],
      },
    ],
  },
  {
    venueId: "v2",
    userEnteredCity: "San Francisco",
    userEnteredState: "CA",
    isGeographic: false,
    geoId: 0,
    woeType: 0,
    localLanguageOrdering: ["English", "Spanish", "French"],
    levels: [
      {
        level: "Neighborhood",
        usedAs: "Neighborhood",
        translations: [
          { isoCode: "en", language: "English", translation: "Fisherman's Wharf" },
          { isoCode: "es", language: "Spanish", translation: "Muelle de los Pescadores" },
          { isoCode: "fr", language: "French", translation: "Fisherman's Wharf" },
          { isoCode: "de", language: "German", translation: "Fisherman's Wharf" },
          { isoCode: "ja", language: "Japanese", translation: "フィッシャーマンズワーフ" },
          { isoCode: "zh", language: "Chinese", translation: "渔人码头" },
        ],
      },
      {
        level: "Locality",
        usedAs: "City",
        geonameId: 5391959,
        translations: [
          { isoCode: "en", language: "English", translation: "San Francisco" },
          { isoCode: "es", language: "Spanish", translation: "San Francisco" },
          { isoCode: "fr", language: "French", translation: "San Francisco" },
          { isoCode: "de", language: "German", translation: "San Francisco" },
          { isoCode: "ja", language: "Japanese", translation: "サンフランシスコ" },
          { isoCode: "zh", language: "Chinese", translation: "旧金山" },
        ],
      },
      {
        level: "Admin Level 2",
        usedAs: null,
        geonameId: 5391997,
        translations: [
          { isoCode: "en", language: "English", translation: "San Francisco County" },
          { isoCode: "fr", language: "French", translation: "Comté de San Francisco" },
          { isoCode: "es", language: "Spanish", translation: "Condado de San Francisco" },
          { isoCode: "zh", language: "Chinese", translation: "旧金山县" },
        ],
      },
      {
        level: "Admin Level 1",
        usedAs: "State",
        geonameId: 5332921,
        translations: [
          { isoCode: "en", language: "English", translation: "California" },
          { isoCode: "es", language: "Spanish", translation: "California" },
          { isoCode: "fr", language: "French", translation: "Californie" },
          { isoCode: "de", language: "German", translation: "Kalifornien" },
          { isoCode: "ja", language: "Japanese", translation: "カリフォルニア州" },
          { isoCode: "zh", language: "Chinese", translation: "加利福尼亚州" },
          { isoCode: "ko", language: "Korean", translation: "캘리포니아주" },
        ],
      },
      {
        level: "Country",
        usedAs: "Country",
        geonameId: 6252001,
        translations: [
          { isoCode: "en", language: "English", translation: "United States" },
          { isoCode: "es", language: "Spanish", translation: "Estados Unidos" },
          { isoCode: "fr", language: "French", translation: "États-Unis" },
          { isoCode: "de", language: "German", translation: "Vereinigte Staaten" },
          { isoCode: "ja", language: "Japanese", translation: "アメリカ合衆国" },
          { isoCode: "zh", language: "Chinese", translation: "美国" },
          { isoCode: "ko", language: "Korean", translation: "미국" },
          { isoCode: "pt", language: "Portuguese", translation: "Estados Unidos" },
        ],
      },
    ],
  },
];

export const MOCK_VENUE_WOES: VenueWoe[] = [
  {
    id: "w1", venueId: "v1", status: "open", type: "info",
    summary: "Incorrect phone number listed",
    description: "phone: +19292842269. The phone number listed for this venue does not match the number on Google Maps or the venue's own website. Multiple users have reported this discrepancy.",
    reportedBy: { id: "u1", name: "Web Discovery Agent 1415809931", role: "reporter", power: 0 },
    reportedAt: "2026-02-26T17:18:57Z",
    woeId: "69a080816db5e0270301a061",
    score: 0, acceptGoal: 4.60, rejectGoal: -1.10, probability: 0.5,
    reasons: "", comments: "fileId: dayuse.com/1772101933971, fileId: dayuse.com/1772101933971",
  },
  {
    id: "w2", venueId: "v1", status: "open", type: "info",
    summary: "Incorrect store ID mapping",
    description: "storeId: ewrsp. The external store ID mapping for this venue appears to be incorrect or outdated. This affects data synchronization with partner systems.",
    reportedBy: { id: "u2", name: "Web Discovery Agent 1415109548", role: "reporter", power: 0 },
    reportedAt: "2025-11-14T11:58:36Z",
    woeId: "6917196c2890d702ddd6d1a4",
    score: 0, acceptGoal: 4.60, rejectGoal: -1.10, probability: 0.5,
    reasons: "", comments: "fileId: ihg.com/1763069710669, fileId: ihg.com/1763069710669",
  },
  {
    id: "w3", venueId: "v1", status: "open", type: "atvc",
    summary: "Attribute verification conflict",
    description: "Multiple attributes for this venue have conflicting information between our database and third-party sources. Requires manual review to determine the correct values.",
    reportedBy: { id: "u2", name: "Web Discovery Agent 1415109548", role: "reporter", power: 0 },
    reportedAt: "2025-11-14T11:58:36Z",
    woeId: "6917196c2890d702ddd6d18e",
    score: 0, acceptGoal: 0.85, rejectGoal: -0.85, probability: 0.5,
    reasons: "", comments: "fileId: ihg.com/1763069710669, fileId: ihg.com/1763069710669",
  },
  {
    id: "w4", venueId: "v1", status: "open", type: "suspicious",
    summary: "Suspicious venue listing",
    description: "This venue listing appears to be suspicious. The address does not correspond to any known business at this location, and the listing may have been created in error or for spam purposes.",
    reportedBy: { id: "u3", name: "unknown user 5445386", role: "reporter", power: 0 },
    reportedAt: "2012-06-06T17:47:36Z",
    woeId: "4fcf97b87b0c00e0162d5480",
    score: 0, acceptGoal: 0.85, rejectGoal: -0.85, probability: 0.5,
    reasons: "", comments: "",
  },
  {
    id: "w5", venueId: "v1", status: "resolved", type: "apa",
    summary: "Reservation link mismatch (Kayak)",
    description: "reservation (699ef10ec2343739de1bacd1): https://www.kayak.com/Elizabeth-Hotels-Crowne-Plaza-Newark-Airport.8244.ksp. The reservation URL points to a different property than expected.",
    reportedBy: { id: "u4", name: "Web Discovery Agent 1415808441", role: "reporter - totalControl", power: -10 },
    reportedAt: "2026-02-27T15:56:50Z", resolvedAt: "2026-03-15T10:30:00Z",
    woeId: "69a1bec242f756667ae32d06",
    score: 10, acceptGoal: 0.85, rejectGoal: -0.85, probability: 1.0,
    reasons: "", comments: "fileId: kayak.com/17721040204702",
  },
  {
    id: "w6", venueId: "v1", status: "resolved", type: "apa",
    summary: "Reservation link mismatch (DayUse)",
    description: "reservation (699ee487fd020d2827843d5c): https://www.dayuse.com/hotels/usa/crowne-plaza-newark-airport. The DayUse reservation link references an outdated property listing.",
    reportedBy: { id: "u1", name: "Web Discovery Agent 1415809931", role: "reporter - totalControl", power: -10 },
    reportedAt: "2026-02-26T17:18:57Z", resolvedAt: "2026-03-12T08:15:00Z",
    woeId: "69a080816db5e0270301a015",
    score: 10, acceptGoal: 0.85, rejectGoal: -0.85, probability: 1.0,
    reasons: "", comments: "fileId: dayuse.com/17721011933971",
  },
  {
    id: "w7", venueId: "v2", status: "open", type: "info",
    summary: "Hours of operation need verification",
    description: "The listed hours of operation may be outdated. Recent visitor reports suggest the cafe now opens earlier on weekdays at 6:30 AM instead of the listed 7:00 AM.",
    reportedBy: { id: "u5", name: "PlaceMaker_SF_2024", role: "superuser", power: 5 },
    reportedAt: "2026-03-10T09:22:00Z",
    woeId: "70a1b2c3d4e5f6a7b8c9d0e1",
    score: 2, acceptGoal: 3.00, rejectGoal: -1.00, probability: 0.65,
    reasons: "Multiple check-in reports confirm earlier opening", comments: "",
  },
  {
    id: "w8", venueId: "v3", status: "open", type: "suspicious",
    summary: "Possible duplicate listing",
    description: "This venue may be a duplicate of another listing in the area. There is a 'Baja Cali Taqueria' at a nearby address that appears to be the same establishment.",
    reportedBy: { id: "u6", name: "GeoValidator_Bot_9001", role: "automated", power: 0 },
    reportedAt: "2026-01-15T14:30:00Z",
    woeId: "71b2c3d4e5f6a7b8c9d0e1f2",
    score: 0, acceptGoal: 2.50, rejectGoal: -0.50, probability: 0.35,
    reasons: "Address proximity match detected", comments: "Potential duplicate of venue v3-alt",
  },
  {
    id: "w9", venueId: "v1", status: "resolved", type: "info",
    summary: "Website URL returns 404",
    description: "The website link listed for this venue returns a 404 error. The domain appears to have expired or the page has been moved.",
    reportedBy: { id: "u7", name: "LinkChecker_Bot_3000", role: "automated", power: 0 },
    reportedAt: "2025-12-01T08:00:00Z", resolvedAt: "2026-01-05T14:20:00Z",
    woeId: "72c3d4e5f6a7b8c9d0e1f2a3",
    score: 8, acceptGoal: 1.20, rejectGoal: -0.60, probability: 0.92,
    reasons: "HTTP 404 detected on automated crawl", comments: "URL updated to new domain",
  },
  {
    id: "w10", venueId: "v1", status: "resolved", type: "apa",
    summary: "Booking.com listing price discrepancy",
    description: "The price shown on the Booking.com integration does not match the actual venue pricing. Difference of approximately 15% detected.",
    reportedBy: { id: "u8", name: "PriceWatch_Agent_102", role: "reporter", power: 0 },
    reportedAt: "2025-10-20T11:30:00Z", resolvedAt: "2025-11-02T09:45:00Z",
    woeId: "73d4e5f6a7b8c9d0e1f2a3b4",
    score: 6, acceptGoal: 2.00, rejectGoal: -0.90, probability: 0.88,
    reasons: "Price mismatch confirmed via API", comments: "fileId: booking.com/298374651",
  },
  {
    id: "w11", venueId: "v1", status: "resolved", type: "atvc",
    summary: "Wi-Fi attribute incorrectly marked as free",
    description: "The venue's Wi-Fi is listed as free but multiple visitors report it requires a purchase or is paid. Attribute needs correction.",
    reportedBy: { id: "u9", name: "Community_Mod_Sarah", role: "moderator", power: 8 },
    reportedAt: "2025-09-15T16:45:00Z", resolvedAt: "2025-09-20T10:00:00Z",
    woeId: "74e5f6a7b8c9d0e1f2a3b4c5",
    score: 12, acceptGoal: 0.85, rejectGoal: -0.85, probability: 0.95,
    reasons: "3 user reports confirm paid Wi-Fi", comments: "",
  },
  {
    id: "w12", venueId: "v1", status: "resolved", type: "suspicious",
    summary: "Spam reviews detected on listing",
    description: "Multiple reviews appear to be generated by bots or fake accounts. Reviews contain similar phrasing and were posted within a short time window.",
    reportedBy: { id: "u10", name: "AntiSpam_System_v4", role: "automated", power: 0 },
    reportedAt: "2025-08-10T03:22:00Z", resolvedAt: "2025-08-12T11:30:00Z",
    woeId: "75f6a7b8c9d0e1f2a3b4c5d6",
    score: 15, acceptGoal: 0.50, rejectGoal: -1.50, probability: 0.97,
    reasons: "Pattern analysis flagged 7 reviews", comments: "Reviews removed, accounts suspended",
  },
  {
    id: "w13", venueId: "v1", status: "resolved", type: "info",
    summary: "Incorrect postal code",
    description: "The postal code listed is 07101 but the correct code for this address is 07114. This affects delivery and navigation services.",
    reportedBy: { id: "u5", name: "PlaceMaker_SF_2024", role: "superuser", power: 5 },
    reportedAt: "2025-07-25T14:10:00Z", resolvedAt: "2025-07-26T08:00:00Z",
    woeId: "76a7b8c9d0e1f2a3b4c5d6e7",
    score: 5, acceptGoal: 3.50, rejectGoal: -0.50, probability: 0.99,
    reasons: "USPS database confirms 07114", comments: "",
  },
  {
    id: "w14", venueId: "v1", status: "resolved", type: "apa",
    summary: "Yelp integration showing wrong venue",
    description: "The Yelp link associated with this venue points to a completely different business. The Yelp ID mapping needs to be corrected.",
    reportedBy: { id: "u4", name: "Web Discovery Agent 1415808441", role: "reporter - totalControl", power: -10 },
    reportedAt: "2025-07-01T19:00:00Z", resolvedAt: "2025-07-10T12:15:00Z",
    woeId: "77b8c9d0e1f2a3b4c5d6e7f8",
    score: 9, acceptGoal: 1.00, rejectGoal: -1.00, probability: 0.91,
    reasons: "Name mismatch between Yelp and FSQ", comments: "fileId: yelp.com/biz/abc123",
  },
  {
    id: "w15", venueId: "v1", status: "resolved", type: "info",
    summary: "Missing accessibility information",
    description: "The venue listing does not include any accessibility information. Wheelchair access, elevator availability, and accessible restrooms should be documented.",
    reportedBy: { id: "u11", name: "AccessibilityReview_2025", role: "reporter", power: 2 },
    reportedAt: "2025-06-18T09:30:00Z", resolvedAt: "2025-07-01T15:00:00Z",
    woeId: "78c9d0e1f2a3b4c5d6e7f8a9",
    score: 3, acceptGoal: 2.00, rejectGoal: -0.30, probability: 0.72,
    reasons: "Accessibility audit flagged missing fields", comments: "Fields populated from on-site survey",
  },
  {
    id: "w16", venueId: "v1", status: "resolved", type: "atvc",
    summary: "Parking attribute conflict",
    description: "The venue is listed as having free parking, but the parking lot now charges a fee. Multiple recent check-ins confirm paid parking.",
    reportedBy: { id: "u9", name: "Community_Mod_Sarah", role: "moderator", power: 8 },
    reportedAt: "2025-06-01T13:00:00Z", resolvedAt: "2025-06-05T09:30:00Z",
    woeId: "79d0e1f2a3b4c5d6e7f8a9b0",
    score: 7, acceptGoal: 1.50, rejectGoal: -0.75, probability: 0.85,
    reasons: "5 check-in tips mention paid parking", comments: "",
  },
  {
    id: "w17", venueId: "v1", status: "resolved", type: "suspicious",
    summary: "Venue may have permanently closed",
    description: "Several indicators suggest this venue may have permanently closed: no recent check-ins, Google listing shows closed, and phone number disconnected.",
    reportedBy: { id: "u6", name: "GeoValidator_Bot_9001", role: "automated", power: 0 },
    reportedAt: "2025-05-10T07:15:00Z", resolvedAt: "2025-05-20T16:45:00Z",
    woeId: "80e1f2a3b4c5d6e7f8a9b0c1",
    score: 4, acceptGoal: 0.85, rejectGoal: -0.85, probability: 0.45,
    reasons: "No check-ins in 90 days", comments: "Venue confirmed open after on-site verification",
  },
  {
    id: "w18", venueId: "v1", status: "resolved", type: "apa",
    summary: "TripAdvisor rating mismatch",
    description: "The TripAdvisor integration shows a 3.2 rating but the actual TripAdvisor page shows 4.1. The rating sync appears to be pulling stale data.",
    reportedBy: { id: "u8", name: "PriceWatch_Agent_102", role: "reporter", power: 0 },
    reportedAt: "2025-04-22T10:00:00Z", resolvedAt: "2025-05-01T08:30:00Z",
    woeId: "81f2a3b4c5d6e7f8a9b0c1d2",
    score: 5, acceptGoal: 1.80, rejectGoal: -0.60, probability: 0.88,
    reasons: "Rating delta exceeds threshold", comments: "Sync job restarted, ratings updated",
  },
  {
    id: "w19", venueId: "v1", status: "resolved", type: "info",
    summary: "Business name changed",
    description: "The venue has rebranded from 'Newark Airport Hotel' to 'Crowne Plaza Newark Airport'. Signage and online presence confirm the new name.",
    reportedBy: { id: "u5", name: "PlaceMaker_SF_2024", role: "superuser", power: 5 },
    reportedAt: "2025-04-01T12:00:00Z", resolvedAt: "2025-04-03T09:00:00Z",
    woeId: "82a3b4c5d6e7f8a9b0c1d2e3",
    score: 10, acceptGoal: 4.00, rejectGoal: -0.50, probability: 0.99,
    reasons: "Name change confirmed via official sources", comments: "",
  },
  {
    id: "w20", venueId: "v1", status: "resolved", type: "atvc",
    summary: "Credit card types outdated",
    description: "The listed accepted credit cards do not include Apple Pay and Google Pay, which the venue now accepts. Contactless payment attributes need updating.",
    reportedBy: { id: "u11", name: "AccessibilityReview_2025", role: "reporter", power: 2 },
    reportedAt: "2025-03-15T14:30:00Z", resolvedAt: "2025-03-20T11:00:00Z",
    woeId: "83b4c5d6e7f8a9b0c1d2e3f4",
    score: 4, acceptGoal: 1.20, rejectGoal: -0.40, probability: 0.78,
    reasons: "On-site photo shows Apple Pay accepted", comments: "",
  },
  {
    id: "w21", venueId: "v1", status: "resolved", type: "suspicious",
    summary: "Duplicate photos from competitor venue",
    description: "Two photos in the gallery appear to be from a different hotel nearby. The interior shots do not match this venue's actual decor.",
    reportedBy: { id: "u10", name: "AntiSpam_System_v4", role: "automated", power: 0 },
    reportedAt: "2025-02-28T06:00:00Z", resolvedAt: "2025-03-05T13:45:00Z",
    woeId: "84c5d6e7f8a9b0c1d2e3f4a5",
    score: 8, acceptGoal: 0.85, rejectGoal: -0.85, probability: 0.82,
    reasons: "Image similarity score > 0.95 with competing venue", comments: "Photos removed from gallery",
  },
  {
    id: "w22", venueId: "v1", status: "resolved", type: "info",
    summary: "Floor count incorrect in listing",
    description: "The venue is listed as having 8 floors but actually has 12 floors after a renovation completed in 2024.",
    reportedBy: { id: "u7", name: "LinkChecker_Bot_3000", role: "automated", power: 0 },
    reportedAt: "2025-02-10T11:20:00Z", resolvedAt: "2025-02-15T08:00:00Z",
    woeId: "85d6e7f8a9b0c1d2e3f4a5b6",
    score: 2, acceptGoal: 1.50, rejectGoal: -0.30, probability: 0.70,
    reasons: "Building records show renovation", comments: "Updated to 12 floors",
  },
  {
    id: "w23", venueId: "v1", status: "resolved", type: "apa",
    summary: "Expedia rate feed discontinued",
    description: "The Expedia rate integration has been returning null values since January. The API endpoint appears to have been deprecated.",
    reportedBy: { id: "u4", name: "Web Discovery Agent 1415808441", role: "reporter - totalControl", power: -10 },
    reportedAt: "2025-01-20T16:00:00Z", resolvedAt: "2025-02-01T10:30:00Z",
    woeId: "86e7f8a9b0c1d2e3f4a5b6c7",
    score: 11, acceptGoal: 0.85, rejectGoal: -0.85, probability: 1.0,
    reasons: "API returns HTTP 410 Gone", comments: "fileId: expedia.com/deprecated/feed-991",
  },
  {
    id: "w24", venueId: "v1", status: "resolved", type: "info",
    summary: "Timezone incorrectly set to EST",
    description: "The venue hours are displayed in EST but the venue observes EDT during daylight saving time. Hours appear off by 1 hour for half the year.",
    reportedBy: { id: "u9", name: "Community_Mod_Sarah", role: "moderator", power: 8 },
    reportedAt: "2025-01-05T09:00:00Z", resolvedAt: "2025-01-08T14:00:00Z",
    woeId: "87f8a9b0c1d2e3f4a5b6c7d8",
    score: 6, acceptGoal: 2.50, rejectGoal: -0.50, probability: 0.93,
    reasons: "DST offset not applied", comments: "Timezone set to America/New_York (auto-adjusts)",
  },
];

// Dashboard-specific mock data for user stats and location intelligence
export interface UserStats {
  id: string;
  name: string;
  avatar: string;
  proposedCount: number;
  approvedCount: number;
  streak: number;
  rank: string;
  rankProgress: number;
  joinedDate: string;
  totalPoints: number;
  weeklyGoal: number;
  weeklyProgress: number;
  achievements: string[];
}

export interface LocationStats {
  homeZone: string;
  totalLocations: number;
  pendingCount: number;
  verifiedCount: number;
  regionHealth: number;
  recentActivity: string;
  topContributors: Array<{
    name: string;
    contributions: number;
  }>;
  weeklyStats: {
    locationsAdded: number;
    verificationsCompleted: number;
    issuesResolved: number;
  };
  regionChallenges: Array<{
    title: string;
    description: string;
    priority: "low" | "medium" | "high";
  }>;
}

// Multiple user profiles for testing different scenarios
export const MOCK_USER_PROFILES: UserStats[] = [
  {
    id: "user-001",
    name: "Alex Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AlexChen&backgroundColor=b6e3f4,c0aede,d1d4f9",
    proposedCount: 127,
    approvedCount: 89,
    streak: 12,
    rank: "Level 4",
    rankProgress: 0.67,
    joinedDate: "2024-08-15",
    totalPoints: 4250,
    weeklyGoal: 15,
    weeklyProgress: 8,
    achievements: ["First Verification", "Week Streak", "Quality Contributor", "Bay Area Expert"],
  },
  {
    id: "user-power",
    name: "Sam Taylor",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&h=160&fit=crop&crop=face",
    proposedCount: 324891,
    approvedCount: 298412,
    streak: 142,
    rank: "Level 9",
    rankProgress: 0.82,
    joinedDate: "2021-03-15",
    totalPoints: 892450,
    weeklyGoal: 50,
    weeklyProgress: 43,
    achievements: ["First Verification", "Week Streak", "Quality Contributor", "Bay Area Expert", "Power User", "Month Streak", "Location Pioneer", "Data Detective", "Community Helper", "Master Verifier"],
  },
  {
    id: "user-002", 
    name: "Maria Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MariaRodriguez&backgroundColor=ffdfbf,ffd5dc,c0aede",
    proposedCount: 245,
    approvedCount: 198,
    streak: 28,
    rank: "Specialist",
    rankProgress: 0.34,
    joinedDate: "2023-12-03",
    totalPoints: 8940,
    weeklyGoal: 20,
    weeklyProgress: 17,
    achievements: ["Power User", "Month Streak", "Location Pioneer", "Data Detective", "Community Helper"],
  },
  {
    id: "user-003",
    name: "Jordan Kim", 
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JordanKim&backgroundColor=d1d4f9,c084fc,a78bfa",
    proposedCount: 67,
    approvedCount: 52,
    streak: 5,
    rank: "Contributor",
    rankProgress: 0.89,
    joinedDate: "2025-01-20",
    totalPoints: 1830,
    weeklyGoal: 10,
    weeklyProgress: 3,
    achievements: ["Quick Start", "Detail Oriented", "Weekend Warrior"],
  },
  {
    id: "user-004",
    name: "Sam Taylor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SamTaylor&backgroundColor=fef3c7,fde68a,facc15",
    proposedCount: 456,
    approvedCount: 423,
    streak: 67,
    rank: "Master",
    rankProgress: 0.12,
    joinedDate: "2023-06-10", 
    totalPoints: 15670,
    weeklyGoal: 25,
    weeklyProgress: 22,
    achievements: ["Legend", "Super Streak", "Regional Champion", "Mentor", "Quality Master", "Speed Demon"],
  }
];

// Multiple location scenarios for different regions
export const MOCK_LOCATION_PROFILES: LocationStats[] = [
  {
    homeZone: "San Francisco Bay Area",
    totalLocations: 2847,
    pendingCount: 142,
    verifiedCount: 2705,
    regionHealth: 0.85,
    recentActivity: "3 places verified today",
    topContributors: [
      { name: "Sam Taylor", contributions: 89 },
      { name: "Maria Rodriguez", contributions: 67 },
      { name: "Alex Chen", contributions: 45 },
      { name: "Jordan Lee", contributions: 38 },
      { name: "Priya Patel", contributions: 34 },
      { name: "Marcus Williams", contributions: 29 },
      { name: "Elena Kim", contributions: 27 },
      { name: "David Nguyen", contributions: 24 },
      { name: "Sarah Mitchell", contributions: 21 },
      { name: "James O'Brien", contributions: 19 },
      { name: "Aisha Johnson", contributions: 17 },
      { name: "Chris Park", contributions: 15 },
      { name: "Olivia Santos", contributions: 13 },
      { name: "Ryan Cooper", contributions: 11 },
      { name: "Mia Thompson", contributions: 9 },
    ],
    weeklyStats: {
      locationsAdded: 23,
      verificationsCompleted: 156,
      issuesResolved: 34,
    },
    regionChallenges: [
      {
        title: "Mission District Data Gap",
        description: "Many venues missing recent hour updates",
        priority: "medium",
      },
      {
        title: "South Bay Expansion",
        description: "New shopping centers need initial mapping",
        priority: "high",
      },
    ],
  },
  {
    homeZone: "Oakland",
    totalLocations: 1243,
    pendingCount: 87,
    verifiedCount: 1156,
    regionHealth: 0.79,
    recentActivity: "5 places verified today",
    topContributors: [
      { name: "Sam Taylor", contributions: 42 },
      { name: "Kenji Watanabe", contributions: 36 },
      { name: "Tanya Brooks", contributions: 31 },
      { name: "Marcus Williams", contributions: 28 },
      { name: "Desiree Malone", contributions: 24 },
      { name: "Victor Reyes", contributions: 19 },
      { name: "Amara Okafor", contributions: 16 },
      { name: "Liam Foster", contributions: 14 },
      { name: "Zoe Chang", contributions: 12 },
      { name: "Priya Patel", contributions: 10 },
    ],
    weeklyStats: {
      locationsAdded: 14,
      verificationsCompleted: 89,
      issuesResolved: 22,
    },
    regionChallenges: [
      {
        title: "Temescal District Growth",
        description: "New restaurants and cafes need initial verification",
        priority: "high",
      },
      {
        title: "Jack London Square Updates",
        description: "Waterfront venues with seasonal hour changes",
        priority: "medium",
      },
    ],
  },
  {
    homeZone: "San Jose",
    totalLocations: 1876,
    pendingCount: 105,
    verifiedCount: 1771,
    regionHealth: 0.82,
    recentActivity: "2 places verified today",
    topContributors: [
      { name: "Sam Taylor", contributions: 28 },
      { name: "Rajesh Kumar", contributions: 52 },
      { name: "Linda Tran", contributions: 44 },
      { name: "Carlos Gutierrez", contributions: 37 },
      { name: "Mei-Lin Wu", contributions: 33 },
      { name: "Derek Hall", contributions: 26 },
      { name: "Priya Patel", contributions: 21 },
      { name: "Jason Kim", contributions: 18 },
      { name: "Fatima Al-Hassan", contributions: 15 },
      { name: "Nathan Brooks", contributions: 12 },
    ],
    weeklyStats: {
      locationsAdded: 18,
      verificationsCompleted: 112,
      issuesResolved: 28,
    },
    regionChallenges: [
      {
        title: "Santana Row Expansion",
        description: "New retail and dining venues need mapping",
        priority: "high",
      },
      {
        title: "Downtown San Jose Revamp",
        description: "Multiple closures and reopenings to track",
        priority: "medium",
      },
      {
        title: "South San Jose Coverage",
        description: "Residential-to-commercial areas need attention",
        priority: "low",
      },
    ],
  },
  {
    homeZone: "Los Angeles",
    totalLocations: 4156,
    pendingCount: 287,
    verifiedCount: 3869,
    regionHealth: 0.78,
    recentActivity: "12 places verified today",
    topContributors: [
      { name: "Carlos Mendoza", contributions: 134 },
      { name: "Jenny Park", contributions: 98 },
      { name: "Mike Johnson", contributions: 76 },
    ],
    weeklyStats: {
      locationsAdded: 45,
      verificationsCompleted: 234,
      issuesResolved: 67,
    },
    regionChallenges: [
      {
        title: "Downtown LA Coverage",
        description: "High venue density needs more contributors",
        priority: "high",
      },
      {
        title: "Beach Cities Updates", 
        description: "Seasonal hour changes not reflected",
        priority: "low",
      },
    ],
  },
  {
    homeZone: "New York Metro",
    totalLocations: 5623,
    pendingCount: 445,
    verifiedCount: 5178,
    regionHealth: 0.72,
    recentActivity: "8 places verified today",
    topContributors: [
      { name: "Ashley Brown", contributions: 156 },
      { name: "David Liu", contributions: 123 },
      { name: "Sofia Garcia", contributions: 98 },
    ],
    weeklyStats: {
      locationsAdded: 67,
      verificationsCompleted: 189,
      issuesResolved: 89,
    },
    regionChallenges: [
      {
        title: "Manhattan Venue Density",
        description: "Too many venues per block causing confusion",
        priority: "high",
      },
      {
        title: "Outer Borough Coverage",
        description: "Queens and Bronx need more attention",
        priority: "medium",
      },
      {
        title: "Transit Integration",
        description: "Subway station venues need category fixes",
        priority: "low",
      },
    ],
  },
  {
    homeZone: "Austin Metro",
    totalLocations: 1234,
    pendingCount: 45,
    verifiedCount: 1189,
    regionHealth: 0.92,
    recentActivity: "5 places verified today",
    topContributors: [
      { name: "Tyler Williams", contributions: 67 },
      { name: "Emma Davis", contributions: 45 },
      { name: "Ryan Martinez", contributions: 34 },
    ],
    weeklyStats: {
      locationsAdded: 12,
      verificationsCompleted: 78,
      issuesResolved: 15,
    },
    regionChallenges: [
      {
        title: "SXSW Venue Updates",
        description: "Festival venues need temporary hour tracking",
        priority: "low",
      },
    ],
  },
  {
    homeZone: "Boston",
    totalLocations: 1987,
    pendingCount: 134,
    verifiedCount: 1853,
    regionHealth: 0.81,
    recentActivity: "4 places verified today",
    topContributors: [
      { name: "Patrick Sullivan", contributions: 78 },
      { name: "Mei-Ling Zhang", contributions: 62 },
      { name: "Connor O'Malley", contributions: 51 },
      { name: "Aisha Patel", contributions: 43 },
      { name: "Derek Lawson", contributions: 37 },
      { name: "Rachel Kim", contributions: 31 },
      { name: "Sam Taylor", contributions: 25 },
      { name: "Thomas Brennan", contributions: 19 },
      { name: "Julia Santos", contributions: 15 },
      { name: "Mark Nguyen", contributions: 12 },
    ],
    weeklyStats: {
      locationsAdded: 19,
      verificationsCompleted: 98,
      issuesResolved: 31,
    },
    regionChallenges: [
      {
        title: "Back Bay Restaurant Boom",
        description: "12 new restaurants opened this month need mapping",
        priority: "high",
      },
      {
        title: "Harvard Square Updates",
        description: "Seasonal campus-area businesses changing hours",
        priority: "medium",
      },
      {
        title: "Seaport District Expansion",
        description: "New development area with unmapped venues",
        priority: "high",
      },
    ],
  },
  {
    homeZone: "Mountain House",
    totalLocations: 312,
    pendingCount: 308,
    verifiedCount: 4,
    regionHealth: 0.01,
    recentActivity: "No activity yet",
    topContributors: [],
    weeklyStats: {
      locationsAdded: 0,
      verificationsCompleted: 0,
      issuesResolved: 0,
    },
    regionChallenges: [
      {
        title: "Brand New Region",
        description: "This community has no active contributors yet — be the first!",
        priority: "high",
      },
    ],
  },
];

// Current active user and location (can be changed for testing)
export const MOCK_USER_STATS: UserStats = MOCK_USER_PROFILES[0];
export const MOCK_LOCATION_STATS: LocationStats = MOCK_LOCATION_PROFILES[0];

// Function to get a random user profile (useful for testing)
export const getRandomUserProfile = (): UserStats => {
  const randomIndex = Math.floor(Math.random() * MOCK_USER_PROFILES.length);
  return MOCK_USER_PROFILES[randomIndex];
};

// Function to get a random location profile (useful for testing)
export const getRandomLocationProfile = (): LocationStats => {
  const randomIndex = Math.floor(Math.random() * MOCK_LOCATION_PROFILES.length);
  return MOCK_LOCATION_PROFILES[randomIndex];
};

// Function to get user by ID
export const getUserById = (id: string): UserStats | undefined => {
  return MOCK_USER_PROFILES.find(user => user.id === id);
};

// Function to get location stats by zone
export const getLocationStatsByZone = (zone: string): LocationStats | undefined => {
  return MOCK_LOCATION_PROFILES.find(location => location.homeZone === zone);
};

export const MOCK_GLOBAL_LEADERBOARD: Array<{ name: string; contributions: number; region: string; streak: number }> = [
  { name: "Carlos Mendoza", contributions: 312, region: "Los Angeles", streak: 45 },
  { name: "Ashley Brown", contributions: 287, region: "New York Metro", streak: 38 },
  { name: "Sam Taylor", contributions: 256, region: "San Francisco Bay Area", streak: 67 },
  { name: "David Liu", contributions: 231, region: "New York Metro", streak: 22 },
  { name: "Jenny Park", contributions: 198, region: "Los Angeles", streak: 31 },
  { name: "Patrick Sullivan", contributions: 176, region: "Boston", streak: 19 },
  { name: "Maria Rodriguez", contributions: 162, region: "San Francisco Bay Area", streak: 28 },
  { name: "Sofia Garcia", contributions: 148, region: "New York Metro", streak: 15 },
  { name: "Rajesh Kumar", contributions: 134, region: "San Jose", streak: 24 },
  { name: "Tyler Williams", contributions: 121, region: "Austin Metro", streak: 17 },
  { name: "Mei-Ling Zhang", contributions: 109, region: "Boston", streak: 21 },
  { name: "Kenji Watanabe", contributions: 97, region: "Oakland", streak: 14 },
  { name: "Alex Chen", contributions: 89, region: "San Francisco Bay Area", streak: 12 },
  { name: "Linda Tran", contributions: 82, region: "San Jose", streak: 9 },
  { name: "Connor O'Malley", contributions: 74, region: "Boston", streak: 11 },
  { name: "Emma Davis", contributions: 68, region: "Austin Metro", streak: 8 },
  { name: "Marcus Williams", contributions: 64, region: "Oakland", streak: 13 },
  { name: "Tanya Brooks", contributions: 59, region: "Oakland", streak: 7 },
  { name: "Desiree Malone", contributions: 55, region: "Oakland", streak: 10 },
  { name: "Victor Reyes", contributions: 51, region: "Oakland", streak: 6 },
  { name: "Ryan Martinez", contributions: 47, region: "Austin Metro", streak: 9 },
  { name: "Jordan Kim", contributions: 43, region: "San Francisco Bay Area", streak: 5 },
  { name: "Fatima Al-Hassan", contributions: 39, region: "San Jose", streak: 8 },
  { name: "Nathan Brooks", contributions: 36, region: "San Jose", streak: 4 },
  { name: "Amara Okafor", contributions: 33, region: "Oakland", streak: 6 },
  { name: "Liam Foster", contributions: 30, region: "Oakland", streak: 5 },
  { name: "Zoe Chang", contributions: 27, region: "Oakland", streak: 3 },
  { name: "Derek Hall", contributions: 24, region: "San Jose", streak: 4 },
  { name: "Rachel Kim", contributions: 21, region: "Boston", streak: 7 },
  { name: "Thomas Brennan", contributions: 18, region: "Boston", streak: 3 },
];

export const MOCK_EPWS: EpwItem[] = [
  { id: "epw-1", name: "Peet's Coffee & Tea", address: "2 Theater Square", city: "Orinda", state: "CA", countryCode: "US", zip: "94563" },
  { id: "epw-2", name: "Zachary's Chicago Pizza", address: "3110 Crow Canyon Pl", city: "San Ramon", state: "CA", countryCode: "US", zip: "94583" },
  { id: "epw-3", name: "La Boulangerie", address: "1228 Broadway", city: "Oakland", state: "CA", countryCode: "US", zip: "94612" },
  { id: "epw-4", name: "Summit Bank", address: "401 Grand Ave", city: "Oakland", state: "CA", countryCode: "US", zip: "94610" },
  { id: "epw-5", name: "Golden Dragon Restaurant", address: "832 Webster St", city: "Oakland", state: "CA", countryCode: "US", zip: "94607" },
  { id: "epw-6", name: "Peet's Coffee", address: "4050 Piedmont Ave", city: "Oakland", state: "CA", countryCode: "US", zip: "94611" },
  { id: "epw-7", name: "Blue Bottle Coffee", address: "4270 Broadway", city: "Oakland", state: "CA", countryCode: "US", zip: "94611" },
  { id: "epw-8", name: "Trader Joe's", address: "5727 College Ave", city: "Oakland", state: "CA", countryCode: "US", zip: "94618" },
  { id: "epw-9", name: "La Piazza Ristorante", address: "15 Moraga Way", city: "Orinda", state: "CA", countryCode: "US", zip: "94563" },
  { id: "epw-10", name: "Safeway", address: "3496 Mt Diablo Blvd", city: "Lafayette", state: "CA", countryCode: "US", zip: "94549" },
  { id: "epw-11", name: "Blue Bottle Coffee", address: "315 Linden St", city: "San Francisco", state: "CA", countryCode: "US", zip: "94102" },
  { id: "epw-12", name: "Philz Coffee", address: "549 Castro St", city: "San Francisco", state: "CA", countryCode: "US", zip: "94114" },
  { id: "epw-13", name: "Sushi Ran", address: "107 Caledonia St", city: "Sausalito", state: "CA", countryCode: "US", zip: "94965" },
  { id: "epw-14", name: "La Boulange de Walnut Creek", address: "1501 Mt Diablo Blvd", city: "Walnut Creek", state: "CA", countryCode: "US", zip: "94596" },
  { id: "epw-15", name: "Pete's Hardware", address: "2162 Chestnut St", city: "San Francisco", state: "CA", countryCode: "US", zip: "94123" },
];
